defaults:
  - base_vlm_local

_target_: models.qwen_model.QwenModel
model_name: qwen2-vl-7b-instruct
weights_path: '${paths.root_dir}/model-weights/Qwen2-VL-7B-Instruct'
batch_size: 8
prompt_format: null
