# config/model/qwen3_vl_30b.yaml
defaults:
  - base_vlm_local
_target_: models.qwen_model.QwenModel
model_name: qwen3-vl-30b-a3b-instruct
weights_path: '../model-weights/Qwen3-VL-30B-A3B-Instruct'
batch_size: 8            # adjust for VRAM
prompt_format: null      # or set if the prompt needs wrapping
