defaults:
  - base_vlm_local
_target_: models.qwen_model.QwenModel
model_name: qwen2.5-VL-7B-Instruct
weights_path: '${paths.root_dir}/model-weights/Qwen2.5-VL-7B-Instruct'
batch_size: 16
prompt_format: null
